import type { Metadata } from "next";
import { Anton } from "next/font/google";
import "./globals.css";

const geistSans = Anton({ weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased mt-8 mx-20`}>
        {children}
      </body>
    </html>
  );
}
